# Actividad 2.3: Pooling, ReLU, Jerarquía de Rasgos y Diseño de una CNN

Objetivo: Diseñar y analizar una CNN básica utilizando capas convolucionales, pooling y densas.

In [ ]:
import tensorflow as tf
import numpy as np

## Parte 1: Analizando una CNN existente

In [ ]:
modelo = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 3), name="entrada"),
    tf.keras.layers.Conv2D(16,(3,3),activation='relu', name="Convolucion_1"),
    tf.keras.layers.MaxPooling2D((2,2), name="Pooling_1"),
    tf.keras.layers.Conv2D(32,(3,3),activation='relu', name="Convolucion_2"),
    tf.keras.layers.MaxPooling2D((2,2), name="Pooling_2"),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64,activation='relu', name="Densa_1"),
    tf.keras.layers.Dense(10,activation='softmax', name="salida")
], name="Mi_CNN")
modelo.summary()

Model: "Mi_CNN"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Convolucion_1 (Conv2D)          │ (None, 30, 30, 16)     │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Pooling_1 (MaxPooling2D)        │ (None, 15, 15, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Convolucion_2 (Conv2D)          │ (None, 13, 13, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Pooling_2 (MaxPooling2D)        │ (None, 6, 6, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Densa_1 (Dense)                 │ (None, 64)             │        73,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ salida (Dense)                  │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 79,530 (310.66 KB)

 Trainable params: 79,530 (310.66 KB)

 Non-trainable params: 0 (0.00 B)

### Pregunta 1
1. ¿Cuántas capas convolucionales posee?
2. ¿Cuántas capas de pooling posee?
3. ¿Cuál es la función de Flatten?
4. ¿Cuál es la función de la última capa Dense?

## Parte 2: Explorando ReLU

In [ ]:
feature_map=np.array([[-3,2,-1],[4,-2,5],[0,-4,3]])
relu=np.maximum(0,feature_map)
print(feature_map)
print(relu)

[[-3  2 -1]
 [ 4 -2  5]
 [ 0 -4  3]]
[[0 2 0]
 [4 0 5]
 [0 0 3]]


### Pregunta 2
1. ¿Qué valores fueron modificados?
2. ¿Qué hace ReLU?
3. ¿Por qué se utiliza frecuentemente en CNN?


## Parte 3: Comparando MaxPooling y AveragePooling

In [ ]:
feature_map=tf.constant([[[[1.],[3.],[2.],[4.]],[[5.],[6.],[1.],[2.]],[[3.],[2.],[8.],[7.]],[[1.],[4.],[6.],[5.]]]])
print("-- MaxPooling2D --")
print(tf.keras.layers.MaxPooling2D((2,2))(feature_map).numpy()[0,:,:,0])
print("-- AveragePooling2D --")
print(tf.keras.layers.AveragePooling2D((2,2))(feature_map).numpy()[0,:,:,0])

-- Feature Map --
[[1. 3. 2. 4.]
 [5. 6. 1. 2.]
 [3. 2. 8. 7.]
 [1. 4. 6. 5.]]
Shape (1, 4, 4, 1)
-- MaxPooling2D --
[[6. 4.]
 [4. 8.]]
-- AveragePooling2D --
[[3.75 2.25]
 [2.5  6.5 ]]


### Pregunta 3
1. ¿Cuál conserva los valores máximos?
2. ¿Cuál genera una representación más suavizada?
3. ¿Qué ventaja tiene reducir el tamaño de los mapas de características?


## Parte 4: Diseñando una CNN

In [ ]:
# Diseñar un modelo de red neuronal convolucional (CNN) con las siguientes capas:
model = tf.keras.Sequential([
    # Capa convolucional
    # Agregar pooling
    # Capa convolucional
    # Agregar pooling
    # Capa convolucional
    # Agregar Flatten
    # Agregar Dense oculta
    # Agregar Dense salida
])


### Pregunta 4
Justifique las decisiones de diseño tomadas.

    - ¿Por qué seleccionó esa cantidad de filtros en cada capa convolucional?
    - ¿Por qué la cantidad de filtros aumenta (o no aumenta) entre capas sucesivas?
    - ¿Por qué incorporó capas de pooling en la arquitectura?
    - ¿Qué función cumple la activación ReLU dentro de la red?
    - ¿Por qué es necesario utilizar una capa Flatten antes de las capas densas?
    - ¿Qué función cumplen las capas Dense en la etapa final de la CNN?
    - ¿Cómo contribuye esta arquitectura a la construcción de una jerarquía de características (bordes → texturas → partes → objetos)?


## Parte 5: Jerarquía de características

Explique cómo evolucionan las características aprendidas por la red:

Bordes → Texturas → Partes → Objetos

## Parte 6: CNN versus MLP

Compare ambas arquitecturas considerando extracción de características, parámetros e información espacial.

## Parte 7: Desafío

Reemplace MaxPooling por AveragePooling y explique las diferencias observadas.

# Parte 8: Analizando la evolución de las características en una CNN

```python
tf.keras.Sequential([
    tf.keras.layers.Input(shape=(32,32,3)),
    tf.keras.layers.Conv2D(16,(3,3),activation='relu',padding='same',name="Conv_1"),
    tf.keras.layers.MaxPooling2D((2,2), name="Polling_1"),
    tf.keras.layers.Conv2D(32,(3,3),activation='relu',padding='same',name="Conv_2"),
    tf.keras.layers.MaxPooling2D((2,2), name="Pooling_2"),
    tf.keras.layers.Conv2D(64,(3,3),activation='relu',padding='same',name="Conv_3"),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64,activation='relu',name="Densa_1"),
    tf.keras.layers.Dense(10,activation='softmax', name="salida")
], name="Otra_CNN")
```


Parte A: Dimensiones espaciales

Complete la siguiente tabla indicando las dimensiones de salida de cada capa.

| Capa                | Dimensión de salida |
| ------------------- | ------------------- |
| Entrada             | 32 × 32 × 3         |
| Conv2D (16 filtros) | ?                   |
| MaxPooling2D        | ?                   |
| Conv2D (32 filtros) | ?                   |
| MaxPooling2D        | ?                   |
| Conv2D (64 filtros) | ?                   |
| Flatten             | ?                   |


Parte B: Jerarquía de características

Indique qué tipo de patrones espera que la red aprenda principalmente en cada etapa.

| Etapa                      | Tipo de características |
| -------------------------- | ----------------------- |
| Primera capa convolucional | ?                       |
| Segunda capa convolucional | ?                       |
| Tercera capa convolucional | ?                       |
| Capa densa final           | ?                       |
